// src/lib/audio_controls/Repeat.svelte
<script>
    export let loopTrack;
    export let isLooping;
    export let currentColor;

    import { IconRepeat } from '@tabler/icons-svelte';
</script>

<button title="Repeat" on:click={loopTrack} style="background-color: {isLooping ? currentColor.background : 'transparent'};" class="rounded-sm p-1">
    <IconRepeat class="h-6 w-6" style="color: {isLooping ? currentColor.text : '#fff'};"/>
</button>

// src/components/audio_controls/Repeat.jsx
import { TbRepeat } from "react-icons/tb";

export default function Repeat(props) {
    return (
        <button
            title="Repeat"
            onClick={props.loopTrack}
            style={{
                backgroundColor: props.isLooping
                    ? props.currentColor.background
                    : "transparent",
            }}
            className="rounded-sm p-1"
        >
            <TbRepeat style={{
                color: props.isLooping ? props.currentColor.text : "#fff",
            }} className="h-6 w-6" />
        </button>
    );
};
