// src/lib/audio_controls/Volume.svelte
<script>
    let {volume, currentColor, oninput} = $props();
    import { IconVolume } from '@tabler/icons-svelte';
</script>

<div class="flex items-center gap-3 justify-self-end">
    <IconVolume class="w-6 h-6 md:w-7 md:h-7 lg:w-8 lg:h-8 text-white" />
    <input title={volume} min="0" max="100" type="range" value={volume} oninput={oninput} class="h-1 cursor-pointer rounded-full w-10 md:w-5" style="accent-color: {currentColor.background};" />
</div>

// src/components/audio_controls/Volume.jsx
import { FaVolumeUp } from "react-icons/fa";

export default function Volume(props) {
    return (
        <div className="flex items-center gap-3 justify-self-end">
            <FaVolumeUp className="h-7 w-7 text-white" />
            <input title={props.volume} min={0} max={100} type="range" onChange={props.changeVolume} value={props.volume}
                className="rounded-full h-1 cursor-pointer"
                style={{ accentColor: `${props.currentColor.background}` }} />

            {/* <input title={props.volume} min={0} max={100} type="range" onChange={props.changeVolume} value={props.volume}
                className="rounded-full h-1 appearance-none outline-none cursor-pointer"
                style={{ background: `linear-gradient(to right, ${props.currentColor.background} ${props.volume}%, ${props.currentColor.text} 0px)`, accentColor: `${props.currentColor.background}` }} /> */}
        </div>
    );
};
