// src/lib/audio_controls/Volume.svelte
<script>
    import { createEventDispatcher } from 'svelte';

    export let volume;
    export let currentColor;

    const dispatch = createEventDispatcher();
</script>

<div class="flex items-center gap-3 justify-self-end">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-volume h-7 w-7 text-white" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M15 8a5 5 0 0 1 0 8"  />
        <path d="M17.7 5a9 9 0 0 1 0 14"  />
        <path d="M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5" fill="currentColor" />
    </svg>
    <input title={volume} min="0" max="100" type="range" on:input={(event) => dispatch('input', { volume: event.target.value })} value={volume} class="rounded-full h-1 cursor-pointer" style="accent-color: {currentColor.background};" />
</div>

// src/components/audio_controls/Volume.tsx
export const Volume = (props: any) => {
  return (
    <div className="flex items-center gap-3 justify-self-end">
      <svg
        className="h-7 w-7 text-white"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
      >
        <path d="M13.5 4.06c0-1.336-1.616-2.005-2.56-1.06l-4.5 4.5H4.508c-1.141 0-2.318.664-2.66 1.905A9.76 9.76 0 001.5 12c0 .898.121 1.768.35 2.595.341 1.24 1.518 1.905 2.659 1.905h1.93l4.5 4.5c.945.945 2.561.276 2.561-1.06V4.06zM18.584 5.106a.75.75 0 011.06 0c3.808 3.807 3.808 9.98 0 13.788a.75.75 0 11-1.06-1.06 8.25 8.25 0 000-11.668.75.75 0 010-1.06z" />
        <path d="M15.932 7.757a.75.75 0 011.061 0 6 6 0 010 8.486.75.75 0 01-1.06-1.061 4.5 4.5 0 000-6.364.75.75 0 010-1.06z" />
      </svg>

      <input
        title={props.volume}
        type="range"
        value={props.volume}
        max={100}
        min={0}
        onChange={props.changeVolume}
        className="h-1"
      />
    </div>
  );
};
