// src/components/audio_controls/AddTrack.jsx
import { TbPlus } from "react-icons/tb";

export default function AddTrack(props) {
    return (
        <button
            title="Add Mp3"
            className="rounded-sm py-1 px-1.5"
            style={{ backgroundColor: props.currentColor.background }}
            onClick={props.openDialog}
        >
            <TbPlus className="h-5 w-5" style={{ color: props.currentColor.text }} />
        </button>
    );
};

// src/lib/audio_controls/AddTrack.svelte
<script>
    export let currentColor;
    export let openDialog;

    import { IconPlus } from '@tabler/icons-svelte';
</script>

<button title="Add Mp3" on:click={openDialog} class="rounded-sm py-0.5 px-1.5" style="background-color: {currentColor.background};">
    <IconPlus class="h-5 w-5" style="color: {currentColor.text};" />
</button>
