// src/components/audio_controls/PlayPauseTrack.jsx
import { TbPlayerPlayFilled, TbPlayerPauseFilled } from "react-icons/tb";


export default function PlayPauseTrack(props) {
    return (
        <button
            title={props.isPlaying ? "Pause" : "Play"} onClick={props.playPauseTrack}
        >

            {props.isPlaying ? (
                <TbPlayerPauseFilled className="h-8 w-8 text-white" />
            ) : (
                <TbPlayerPlayFilled className="h-8 w-8 text-white" />
            )}
        </button>
    );
};

// src/lib/audio_controls/PlayPauseTrack.svelte
<script>
    export let isPlaying;
    export let playPauseTrack;
</script>

<button title={isPlaying ? "Pause" : "Play"} on:click={playPauseTrack}>
    {#if isPlaying}
    <i class="fa-solid fa-pause fa-xl text-white"></i>
    {:else}
    <i class="fa-solid fa-play fa-xl text-white"></i>
    {/if}
</button>
