// src/components/audio_controls/ShuffleTrack.jsx
import { TbArrowsShuffle } from "react-icons/tb";

export default function ShuffleTrack(props) {
    return (
        <button
            title="shuffle"
            onClick={props.shuffleTrack}
            style={{
                backgroundColor: props.isShuffling
                    ? props.currentColor.background
                    : "transparent",
            }}
            className="rounded-sm p-1"
        >
            <TbArrowsShuffle style={{
                color: props.isShuffling ? props.currentColor.text : "#fff",
            }} className="h-6 w-6" />
        </button>
    );
};

// src/lib/audio_controls/ShuffleTrack.svelte
<script>
    export let shuffleTrack;
    export let isShuffling;
    export let currentColor;
    
    import { IconArrowsShuffle } from '@tabler/icons-svelte';
</script>

<button title="shuffle" on:click={shuffleTrack} style="background-color: {isShuffling ? currentColor.background : 'transparent'};" class="rounded-sm p-1" >
    <IconArrowsShuffle class="h-6 w-6" style="color: {isShuffling ? currentColor.text : '#fff'};"/>
</button>
